#!/usr/bin/env node

/**
 * Stripe Setup Script for CHRONOS Financial
 *
 * This script helps set up Stripe for testing the subscription system.
 * Run this after setting up your Stripe test account.
 */

const readline = require('readline')
const fs = require('fs')
const path = require('path')

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
})

function question(query) {
  return new Promise(resolve => rl.question(query, resolve))
}

async function main() {
  console.log('🚀 CHRONOS Financial - Stripe Setup\n')
  console.log('This script will help you configure Stripe for testing.\n')

  // Get Stripe credentials
  console.log('📝 Please enter your Stripe test credentials:')
  const secretKey = await question('Stripe Secret Key (sk_test_...): ')
  const publishableKey = await question('Stripe Publishable Key (pk_test_...): ')
  const webhookSecret = await question('Webhook Secret (whsec_..., optional): ')

  // Get price IDs (optional)
  console.log('\n💰 Price IDs (optional - leave empty to use defaults):')
  const starterPriceId = await question('Starter Price ID (default: price_starter): ') || 'price_starter'
  const proMonthlyPriceId = await question('Pro Monthly Price ID (default: price_pro_monthly): ') || 'price_pro_monthly'
  const proYearlyPriceId = await question('Pro Yearly Price ID (default: price_pro_yearly): ') || 'price_pro_yearly'

  // Create .env.local file
  const envContent = `# Stripe Configuration (Generated by setup script)
STRIPE_SECRET_KEY=${secretKey}
STRIPE_PUBLISHABLE_KEY=${publishableKey}
${webhookSecret ? `STRIPE_WEBHOOK_SECRET=${webhookSecret}` : '# STRIPE_WEBHOOK_SECRET=whsec_your_webhook_secret'}

# Stripe Price IDs
STRIPE_STARTER_PRICE_ID=${starterPriceId}
STRIPE_PRO_MONTHLY_PRICE_ID=${proMonthlyPriceId}
STRIPE_PRO_YEARLY_PRICE_ID=${proYearlyPriceId}

# Other environment variables (add as needed)
NEXTAUTH_SECRET=your_nextauth_secret_here
NEXTAUTH_URL=http://localhost:3000
`

  const envPath = path.join(process.cwd(), '.env.local')
  fs.writeFileSync(envPath, envContent)

  console.log('\n✅ Environment file created at .env.local')

  // Display next steps
  console.log('\n📋 Next Steps:')
  console.log('1. Restart your development server: npm run dev')
  console.log('2. Create products and prices in Stripe Dashboard:')
  console.log('   - Starter Plan: $0/month')
  console.log('   - Pro Monthly: $29/month')
  console.log('   - Pro Yearly: $278/year')
  console.log('3. Update the price IDs in .env.local with actual Stripe price IDs')
  console.log('4. Set up webhook endpoint: https://your-domain.com/api/stripe/webhooks')
  console.log('5. Test webhook signatures using: /api/stripe/test-webhook')

  if (!webhookSecret) {
    console.log('\n⚠️  WARNING: No webhook secret provided.')
    console.log('   Webhooks will not work until you add STRIPE_WEBHOOK_SECRET to .env.local')
  }

  console.log('\n🎉 Stripe setup complete!')

  rl.close()
}

main().catch(error => {
  console.error('❌ Setup failed:', error)
  rl.close()
  process.exit(1)
})